version: "2.1"
services:
     webserver:
          build:
               context: .
               dockerfile: frontend.Dockerfile
          container_name: syno_downloadlist_frontend
          ports:
               - "9000:80"
          volumes:
              - "./app:/app"
              - "./resources/synodownload-resources:/app/resources"
          environment:
               - SYNOLOGY_HOST=[localhost]
               - SYNOLOGY_PORT=[port]
               - SYNOLOGY_USERNAME=[username]
               - SYNOLOGY_PASSWORD=[password]
               - IPLOOKUP_HOST=${SYNOLOGY_IPLOOKUP_HOST}
               - IPLOOKUP_PORT=8080
          links:
               - ipaddress_lookup
     ipaddress_lookup:
          image: fiorix/freegeoip
          container_name: syno_downloadlist_iplookup
          ports:
               - "3012:8080"
