FROM php:5.6-alpine
MAINTAINER FAN ZHISHEN <thedarkprincedc@yahoo.com>
ARG SYNOLOGY_HOST
ARG SYNOLOGY_PORT
ARG SYNOLOGY_IPLOOKUP_HOST
ARG SYNOLOGY_IPLOOKUP_PORT

ENV SYNOLOGY_HOST ${SYNOLOGY_HOST}
ENV SYNOLOGY_PORT ${SYNOLOGY_PORT}
ENV SYNOLOGY_IPLOOKUP_HOST ${SYNOLOGY_IPLOOKUP_HOST}
ENV SYNOLOGY_IPLOOKUP_PORT ${SYNOLOGY_IPLOOKUP_PORT}

COPY app /var/www/html
EXPOSE 80/tcp

CMD php -S 0.0.0.0:80 -t /var/www/html
